//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public int id { get; set; }
        public string name { get; set; }
        public string headquarters { get; set; }
        public string website { get; set; }
        public string description { get; set; }
        public string avatar { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public int recruiter_id { get; set; }
    
        public virtual recruiter recruiter { get; set; }
    }
}
