//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone2021
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCapstonePrototypeEntities : DbContext
    {
        public DbCapstonePrototypeEntities()
            : base("name=DbCapstonePrototypeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<cv> cvs { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<recruiter> recruiters { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<student_apply_job> student_apply_job { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
