//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class manager_deny_job
    {
        public int id { get; set; }
        public int recruiter_id { get; set; }
        public string deny_message { get; set; }
        public int job_id { get; set; }
        public int manager_id { get; set; }
    
        public virtual job job { get; set; }
        public virtual manager manager { get; set; }
        public virtual recruiter recruiter { get; set; }
    }
}
